function SVM_Multi(FileName,DirectoryName)

ones(10)*ones(10);

WorkingfileName = FileName;

length_of_file_name = length(WorkingfileName);
length_file_name_without_extention = length_of_file_name - 4;
ChosenMatrix = WorkingfileName(1:length_file_name_without_extention);
ChosenFeatures = ChosenMatrix;
    
toWorkWith = sprintf('%s/%s',DirectoryName, WorkingfileName);

% load the features to work with
 load(toWorkWith)
    
    % Start by removing outliers
 [InX,InY,NumberRemoved] = RemoveOutliers(InX,InY);
    
    % Normalize columns to have mean 0, std 1
    
  InX = zscore(InX);
    
 [NumberOfInstances,NumberOfFeatures] = size(InX);
    
    %Methods
    % CFS
    % FCBF
    % Fisher

    % Multi-Class
    [CFS_M,cfs_columns,...
    FCBF_M,fcbf_columns,Fisher_M,...
    fisher_columns] = FSMyMatrix(InX,InY);

    % Original Matrix Multi Class
[Orig_SVM_Precision_Macro,...
 Orig_SVM_Precision_micro,...
 Orig_SVM_Recall_Macro,...
 Orig_SVM_Recall_micro,...
 Orig_SVM_F1Score_Macro,...
 Orig_SVM_F1Score_micro, ...
 Orig_SVM_Final__Accuracy,...
 Orig_SVM_Best_Cost,...
 Orig_SVM_Best_Gamma,...
 Orig_SVM_Final_ConfMatrix,...
 Orig_SVM_Final_Inconclusive] ...
    = RunMySVM(InX,InY);

WriteMySVMFile(ChosenFeatures,...
'Original_Matrix',...
'MultiClass',...
Orig_SVM_Precision_Macro,...
 Orig_SVM_Precision_micro,...
 Orig_SVM_Recall_Macro,...
 Orig_SVM_Recall_micro,...
 Orig_SVM_F1Score_Macro,...
 Orig_SVM_F1Score_micro, ...
 Orig_SVM_Final__Accuracy,...
 Orig_SVM_Best_Cost,...
 Orig_SVM_Best_Gamma,...
 Orig_SVM_Final_ConfMatrix,...
 Orig_SVM_Final_Inconclusive);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%CFS Multi Class
[CFS_SVM_Precision_Macro,...
 CFS_SVM_Precision_micro,...
 CFS_SVM_Recall_Macro,...
 CFS_SVM_Recall_micro,...
 CFS_SVM_F1Score_Macro,...
 CFS_SVM_F1Score_micro, ...
 CFS_SVM_Final__Accuracy,...
 CFS_SVM_Best_Cost,...
 CFS_SVM_Best_Gamma,...
 CFS_SVM_Final_ConfMatrix,...
 CFS_SVM_Final_Inconclusive] ...
    = RunMySVM(CFS_M,InY);

WriteMySVMFile(ChosenFeatures,...
'CFS_Matrix',...
'MultiClass',...
CFS_SVM_Precision_Macro,...
 CFS_SVM_Precision_micro,...
 CFS_SVM_Recall_Macro,...
 CFS_SVM_Recall_micro,...
 CFS_SVM_F1Score_Macro,...
 CFS_SVM_F1Score_micro, ...
 CFS_SVM_Final__Accuracy,...
 CFS_SVM_Best_Cost,...
 CFS_SVM_Best_Gamma,...
 CFS_SVM_Final_ConfMatrix,...
 CFS_SVM_Final_Inconclusive);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%FCBF Multi Class
[FCBF_SVM_Precision_Macro,...
 FCBF_SVM_Precision_micro,...
 FCBF_SVM_Recall_Macro,...
 FCBF_SVM_Recall_micro,...
 FCBF_SVM_F1Score_Macro,...
 FCBF_SVM_F1Score_micro, ...
 FCBF_SVM_Final__Accuracy,...
 FCBF_SVM_Best_Cost,...
 FCBF_SVM_Best_Gamma,...
 FCBF_SVM_Final_ConfMatrix,...
 FCBF_SVM_Final_Inconclusive] ...
    = RunMySVM(FCBF_M,InY);

WriteMySVMFile(ChosenFeatures,...
'FCBF_Matrix',...
'MultiClass',...
FCBF_SVM_Precision_Macro,...
 FCBF_SVM_Precision_micro,...
 FCBF_SVM_Recall_Macro,...
 FCBF_SVM_Recall_micro,...
 FCBF_SVM_F1Score_Macro,...
 FCBF_SVM_F1Score_micro, ...
 FCBF_SVM_Final__Accuracy,...
 FCBF_SVM_Best_Cost,...
 FCBF_SVM_Best_Gamma,...
 FCBF_SVM_Final_ConfMatrix,...
 FCBF_SVM_Final_Inconclusive);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fisher Multi Class
[Fisher_SVM_Precision_Macro,...
 Fisher_SVM_Precision_micro,...
 Fisher_SVM_Recall_Macro,...
 Fisher_SVM_Recall_micro,...
 Fisher_SVM_F1Score_Macro,...
 Fisher_SVM_F1Score_micro, ...
 Fisher_SVM_Final__Accuracy,...
 Fisher_SVM_Best_Cost,...
 Fisher_SVM_Best_Gamma,...
 Fisher_SVM_Final_ConfMatrix,...
 Fisher_SVM_Final_Inconclusive] ...
    = RunMySVM(Fisher_M,InY);

WriteMySVMFile(ChosenFeatures,...
'Fisher_Matrix',...
'MultiClass',...
Fisher_SVM_Precision_Macro,...
 Fisher_SVM_Precision_micro,...
 Fisher_SVM_Recall_Macro,...
 Fisher_SVM_Recall_micro,...
 Fisher_SVM_F1Score_Macro,...
 Fisher_SVM_F1Score_micro, ...
 Fisher_SVM_Final__Accuracy,...
 Fisher_SVM_Best_Cost,...
 Fisher_SVM_Best_Gamma,...
 Fisher_SVM_Final_ConfMatrix,...
 Fisher_SVM_Final_Inconclusive);

end