%MATLAB 2013 has issues with BLAS TLS libraries, so need to run 
% ones(10)*ones(10)

ones(10)*ones(10);
% Load in matrices.
% ask what matrix and what class labels (Binary/Multi class

List_files_in_features = dir('features');

List_files_in_Months = dir('Months');

List_files_in_Weeks = dir('Weeks');

%Multi class
%{
for file_index = 3:length(List_files_in_features)
    
    WorkingfileName = List_files_in_features(file_index).name;
    
    % Want to get the name of the features we are working with
    length_of_file_name = length(WorkingfileName);
    length_file_name_without_extention = length_of_file_name - 4;
    ChosenMatrix = WorkingfileName(1:length_file_name_without_extention);
    ChosenFeatures = ChosenMatrix;
    
    toWorkWith = sprintf('features/%s',WorkingfileName);
    
    % load the features to work with
    load(toWorkWith)
    
    % Start by removing outliers
    [InX,InY,NumberRemoved] = RemoveOutliers(InX,InY);
    
    % Normalize columns to have mean 0, std 1
    
    InX = zscore(InX);
    
    [NumberOfInstances,NumberOfFeatures] = size(InX);
    
    %Methods
    % CFS
    % FCBF
    % Fisher

    % Multi-Class
    [CFS_M,cfs_columns,...
    FCBF_M,fcbf_columns,Fisher_M,...
    fisher_columns] = FSMyMatrix(InX,InY);



%My Original Matrix Multi Class
[Orig_LDA_Precision_micro,...
Orig_LDA_Precision_Macro,...
Orig_LDA_Recall_micro,...
Orig_LDA_Recall_Macro,...
Orig_LDA_Fscore_Macro,...
Orig_LDA_Fscore_micro,...
Orig_LDA_Acc,...
Orig_LDA_Confusion]...
= RunMyLDA(InX,InY);


WriteMyLDAFile(ChosenFeatures,...
'Original_Matrix',...
'MultiClass',...
Orig_LDA_Precision_micro,...
Orig_LDA_Precision_Macro,...
Orig_LDA_Recall_micro,...
Orig_LDA_Recall_Macro,...
Orig_LDA_Fscore_Macro,...
Orig_LDA_Fscore_micro,...
Orig_LDA_Acc,...
Orig_LDA_Confusion);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%CFS Multi Class
[CFS_LDA_Precision_micro,...
CFS_LDA_Precision_Macro,...
CFS_LDA_Recall_micro,...
CFS_LDA_Recall_Macro,...
CFS_LDA_Fscore_Macro,...
CFS_LDA_Fscore_micro,...
CFS_LDA_Acc,...
CFS_LDA_Confusion]...
= RunMyLDA(CFS_M,InY);

WriteMyLDAFile(ChosenFeatures,...
'CFS_Matrix',...
'MultiClass',...
CFS_LDA_Precision_micro,...
CFS_LDA_Precision_Macro,...
CFS_LDA_Recall_micro,...
CFS_LDA_Recall_Macro,...
CFS_LDA_Fscore_Macro,...
CFS_LDA_Fscore_micro,...
CFS_LDA_Acc,...
CFS_LDA_Confusion);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FCBF Multi Class
[FCBF_LDA_Precision_micro,...
FCBF_LDA_Precision_Macro,...
FCBF_LDA_Recall_micro,...
FCBF_LDA_Recall_Macro,...
FCBF_LDA_Fscore_Macro,...
FCBF_LDA_Fscore_micro,...
FCBF_LDA_Acc,...
FCBF_LDA_Confusion]...
= RunMyLDA(FCBF_M,InY);

WriteMyLDAFile(ChosenFeatures,...
'FCBF_Matrix',...
'MultiClass',...
FCBF_LDA_Precision_micro,...
FCBF_LDA_Precision_Macro,...
FCBF_LDA_Recall_micro,...
FCBF_LDA_Recall_Macro,...
FCBF_LDA_Fscore_Macro,...
FCBF_LDA_Fscore_micro,...
FCBF_LDA_Acc,...
FCBF_LDA_Confusion);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fisher Multi Class
[Fisher_LDA_Precision_micro,...
Fisher_LDA_Precision_Macro,...
Fisher_LDA_Recall_micro,...
Fisher_LDA_Recall_Macro,...
Fisher_LDA_Fscore_Macro,...
Fisher_LDA_Fscore_micro,...
Fisher_LDA_Acc,...
Fisher_LDA_Confusion]...
= RunMyLDA(Fisher_M,InY);

WriteMyLDAFile(ChosenFeatures,...
'Fisher_Matrix',...
'MultiClass',...
Fisher_LDA_Precision_micro,...
Fisher_LDA_Precision_Macro,...
Fisher_LDA_Recall_micro,...
Fisher_LDA_Recall_Macro,...
Fisher_LDA_Fscore_Macro,...
Fisher_LDA_Fscore_micro,...
Fisher_LDA_Acc,...
Fisher_LDA_Confusion);
    

end
%}

%Binary
for file_index = 3:length(List_files_in_features)
    
    WorkingfileName = List_files_in_features(file_index).name;
    
    % Want to get the name of the features we are working with
    length_of_file_name = length(WorkingfileName);
    length_file_name_without_extention = length_of_file_name - 4;
    ChosenMatrix = WorkingfileName(1:length_file_name_without_extention);
    ChosenFeatures = ChosenMatrix;
    
    toWorkWith = sprintf('features/%s',WorkingfileName);
    
    % load the features to work with
    load(toWorkWith)
    
    BInY = BinarizeMyClassLabels(InY);
    
    % Start by removing outliers
    [InX,BInY,NumberRemoved] = RemoveOutliers(InX,BInY);

    % Balance The classes
    
    [InX,BInY] = EvenMyBinaryClasses(InX,BInY);
    
    % Normalize columns to have mean 0, std 1
    
    InX = zscore(InX);
    
    [NumberOfInstances,NumberOfFeatures] = size(InX);
    
    % Binary-Class
    [CFS_B,cfs_bin_columns,FCBF_B,fcbf_bin_columns,...
    Fisher_B,fisher_bin_columns] = FSMyMatrix(InX,BInY);
    
  
% LDA Binary

% Binary


%My Original Matrix `Binay Class
[Orig_B_LDA_Precision_micro,...
Orig_B_LDA_Precision_Macro,...
Orig_B_LDA_Recall_micro,...
Orig_B_LDA_Recall_Macro,...
Orig_B_LDA_Fscore_Macro,...
Orig_B_LDA_Fscore_micro,...
Orig_B_LDA_Acc,...
Orig_B_LDA_Confusion]...
= RunMyLDA(InX,BInY);

WriteMyLDAFile(ChosenFeatures,...
'Original_Matrix',...
'Binary',...
Orig_B_LDA_Precision_micro,...
Orig_B_LDA_Precision_Macro,...
Orig_B_LDA_Recall_micro,...
Orig_B_LDA_Recall_Macro,...
Orig_B_LDA_Fscore_Macro,...
Orig_B_LDA_Fscore_micro,...
Orig_B_LDA_Acc,...
Orig_B_LDA_Confusion);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%CFS Bin Class
[CFS_B_LDA_Precision_micro,...
CFS_B_LDA_Precision_Macro,...
CFS_B_LDA_Recall_micro,...
CFS_B_LDA_Recall_Macro,...
CFS_B_LDA_Fscore_Macro,...
CFS_B_LDA_Fscore_micro,...
CFS_B_LDA_Acc,...
CFS_B_LDA_Confusion]...
= RunMyLDA(CFS_B,BInY);

WriteMyLDAFile(ChosenFeatures,...
'CFS_Matrix',...
'Binary',...
CFS_B_LDA_Precision_micro,...
CFS_B_LDA_Precision_Macro,...
CFS_B_LDA_Recall_micro,...
CFS_B_LDA_Recall_Macro,...
CFS_B_LDA_Fscore_Macro,...
CFS_B_LDA_Fscore_micro,...
CFS_B_LDA_Acc,...
CFS_B_LDA_Confusion);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% FCBF Binary Class
[FCBF_B_LDA_Precision_micro,...
FCBF_B_LDA_Precision_Macro,...
FCBF_B_LDA_Recall_micro,...
FCBF_B_LDA_Recall_Macro,...
FCBF_B_LDA_Fscore_Macro,...
FCBF_B_LDA_Fscore_micro,...
FCBF_B_LDA_Acc,...
FCBF_B_LDA_Confusion]...
= RunMyLDA(FCBF_B,BInY);

WriteMyLDAFile(ChosenFeatures,...
'FCBF_Matrix',...
'Binary',...
FCBF_B_LDA_Precision_micro,...
FCBF_B_LDA_Precision_Macro,...
FCBF_B_LDA_Recall_micro,...
FCBF_B_LDA_Recall_Macro,...
FCBF_B_LDA_Fscore_Macro,...
FCBF_B_LDA_Fscore_micro,...
FCBF_B_LDA_Acc,...
FCBF_B_LDA_Confusion);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Fisher Binary Class
[Fisher_B_LDA_Precision_micro,...
Fisher_B_LDA_Precision_Macro,...
Fisher_B_LDA_Recall_micro,...
Fisher_B_LDA_Recall_Macro,...
Fisher_B_LDA_Fscore_Macro,...
Fisher_B_LDA_Fscore_micro,...
Fisher_B_LDA_Acc,...
Fisher_B_LDA_Confusion]...
= RunMyLDA(Fisher_B,BInY);

WriteMyLDAFile(ChosenFeatures,...
'Fisher_Matrix',...
'Binary',...
Fisher_B_LDA_Precision_micro,...
Fisher_B_LDA_Precision_Macro,...
Fisher_B_LDA_Recall_micro,...
Fisher_B_LDA_Recall_Macro,...
Fisher_B_LDA_Fscore_Macro,...
Fisher_B_LDA_Fscore_micro,...
Fisher_B_LDA_Acc,...
Fisher_B_LDA_Confusion);
end